chapter25/accounts/urls.py
from django.urls import path

from .views import send_login_email, login, logout

urlpatterns = [
    path('send_login_email', send_login_email, name='send_login_email'),
    path('login', login, name='login'),
    path('logout', logout, name='logout')
]

chapter25/lists/urls.py
from django.urls import path
from lists.views import new_list, view_list, my_lists, share_list

urlpatterns = [
    path('new', new_list, name='new_list'),
    path('<int:list_id>/', view_list, name='view_list'),
    path('<int:list_id>/share', share_list, name='share_list'),
    path('users/<str:email>/', my_lists, name='my_lists'),
]

chapter25/superlists/urls.py
from django.urls import path, include

from lists.views import home_page

urlpatterns = [
    path('', home_page, name='home'),
    path('lists/', include('lists.urls')),
    path('accounts/', include('accounts.urls'))
]

chapter25/accounts/models.py
import uuid
from django.db import models


class User(models.Model):
    email = models.EmailField(primary_key=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    uid = models.CharField(
        max_length=40, default=uuid.uuid4, unique=True
    )
    email = models.EmailField()

chapter25/lists/models.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import models
from django.urls import reverse

User = get_user_model()


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey('List', default=None, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')


class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='shared_with'
    )

    def get_absolute_url(self):
        res = reverse('view_list', args=[self.id])
        return res
    
    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_

    @property
    def name(self):
        return self.item_set.first().text

chapter25/lists/forms.py
from django import forms

from .models import Item, List

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            })
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(
                first_item_text=self.cleaned_data['text'],
                owner=owner
            )
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])



class ExistingListItemForm(ItemForm):
    def __init__(self, for_list: List, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self) -> None:
        try:
            self.instance.validate_unique()
        except forms.ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)
        return super().validate_unique()

chapter25/accounts/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import auth, messages
from django.shortcuts import redirect
from django.urls import reverse

from accounts.models import Token


def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token=' + str(token.uid)
    )
    message_body = f'Use this link to log in:\n\n{url}'
    send_mail(
        'Your login link for Superlists',
        message_body,
        settings.EMAIL_HOST_USER,
        [email],
    )
    messages.success(
        request,
        'Проверьте свою почту, мы отправили Вам ссылку, которую можно'
        ' использовать для входа на сайт.'
    )
    return redirect('/')


def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')


def logout(request):
    auth.logout(request)
    return redirect('/')

chapter25/lists/views.py
import time
from typing import Optional

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import User
from lists.forms import ExistingListItemForm, ItemForm, NewListForm
from lists.models import List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, 'form': form})


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def share_list(request, list_id: int):
    if request.method == 'POST':
        list_ = get_object_or_404(List, id=list_id)
        
        if request.user == list_.owner:
            user_append_email = request.POST.get('sharee')
            user = _get_user_or_add_messages(request, user_append_email)
            if user:
                list_.shared_with.add(user_append_email)
                list_.save()
            return redirect('view_list', list_id=list_id)
    return redirect('/')


def my_lists(request, email: str):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})


def _get_user_or_add_messages(request, user_email: str) -> Optional[User]:
    """Получить пользователя по email или добавить сообщение в messages"""
    try:
        return User.objects.get(email=user_email)
    except User.DoesNotExist:
        messages.error(request, 'Пользователь не найден!')

chapter25/lists/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  
  <head>
    <title>To-Do lists</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>
  
  <body>
    <div class="container">
      
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Superlists</a>
          {% if user.email %}
          <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="navbar-text">Logged in as {{ user.email }}</li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
          </ul>
          {% else %}
          <form
            class="navbar-form navbar-right"
            method="POST"
            action="{% url 'send_login_email' %}"
          >
            <span>Enter email to log in:</span>
            <input class="form-control" name="email" type="text"/>
            {% csrf_token %}
          </form>
          {% endif %}
        </div>
      </nav>

      {% if messages %}
      <div class="row">
        <div class="col-md-8">
          {% for message in messages %}
            {% if message.level_tag == 'success' %}
              <div class="alert alert-success">{{ message }}</div>
            {% else %}
              <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
          {% endfor %}
        </div>
      </div>
      {% endif %}

      <div class="row">
        <div class="col-md-12 cold-md-offset-3 jumbotron">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            {% block list_form %}
              <form method="POST" action="{% block form_action %}{% endblock %}">
                {{ form.text }}
                {% csrf_token %}
                {% if form.errors %}
                  <div class="form-group has-error">
                    <div class="help-block">{{ form.text.errors }}</div>
                  </div>
                {% endif %}
              </form>
            {% endblock %}
          </div>
        </div>
      </div>
  
      <div class="row">
        <div class="col-md-12 cold-md-offset-3">
          {% block table %}
          {% endblock %}
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 cold-md-offset-3">
          {% block extra_content %}
          {% endblock %}
        </div>
      </div>

    </div>

    <script src="{% static 'lists.js' %}"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function(){
        window.SuperLists.initialize();
      })
    </script>
  </body>

</html>

chapter25/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

chapter25/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
  <table class="table" id="id_list_table">
    {% for item in list.item_set.all %}
    <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    {% endfor %}
  </table>
  <div class="row">
    <div class="col-md-6">
      {% if list.owner == user %}
      <p>
        <h3>Список предоставлен в общее пользование для:</h3>
      </p>
      <ul class="list-sharee">
        {% for user in list.shared_with.all %}
        <li>{{ user.email }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <p>
        <h3>Владелец списка: <span id="id_list_owner">{{ list.owner.email }}</span></h3>
      </p>
      {% endif %}
    </div>
    <form class="col-md-6" method="POST" action="{% url 'share_list' list_id=list.id %}">
      {% csrf_token %}
      <p>
        <h3>
          Поделиться этим списком
        </h3>
      </p>
      <input name="sharee" placeholder="your@friend-email.com" class="form-control"/>
    </form>

  </div>
{% endblock %}

chapter25/lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul id="lists">
        {% for list in owner.shared_with.all %}
        <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
        
        {% for list in owner.list_set.all %}
        <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}